spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      order_inserts: true
      order_updates: true
      batch_versioned_data: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:${POSTGRESQL.ADDON_TYPE}://${POSTGRESQL.ADDON_HOST}:${POSTGRESQL.ADDON_PORT}/${POSTGRESQL.ADDON_DB}?reconnect=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=${POSTGRESQL.ADDON_TIME_ZONE}
    username: ${ADDON_USER}
    password: ${ADDON_PASSWORD}
    hikari:
      maximum-pool-size: 1
  flyway:
    enabled: true

POSTGRESQL:
  ADDON_DB: ${ADDON_DB}
  ADDON_HOST: ${ADDON_HOST}
  ADDON_PORT: ${ADDON_PORT:5432}
  ADDON_TYPE: ${ADDON_TYPE:postgresql}
  ADDON_TIME_ZONE: ${TIME_ZONE:Europe/Moscow}

server:
  port: ${PORT:8080}
